/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cohortes;

import static cohortes.Connexion.cnx;
import static cohortes.Connexion.rst;
import static cohortes.Rechercher.st;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Chachou
 */
public class Lister extends javax.swing.JFrame {
    
     static Connection cnx;
    static Statement st;
    static ResultSet rst;
    
     private static Connection  connecterDB(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/ptut?zeroDateTimeBehavior=convertToNull";
            String user="root";
            String password="";
            Connection cnx=DriverManager.getConnection(url,user,password);
            return cnx;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
     }
   
    /**
     * Creates new form Connexion
     */
    public Lister() {
        initComponents();
        cnx=connecterDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pann_cohortes = new javax.swing.JPanel();
        lbl_titre = new javax.swing.JLabel();
        ImageIcon image=new ImageIcon("src/gif/Logo.jpg");
        lbl_logo = new javax.swing.JLabel(image);
        bt_deco = new javax.swing.JButton();
        lbl_nompage = new javax.swing.JLabel();
        pann_menu = new javax.swing.JPanel();
        bt_rechercher = new javax.swing.JButton();
        bt_afficher = new javax.swing.JButton();
        bt_lister = new javax.swing.JButton();
        pann_lister = new javax.swing.JPanel();
        pann_recherche = new javax.swing.JPanel();
        lbl_annee = new javax.swing.JLabel();
        text_annee = new javax.swing.JTextField();
        lbl_intitule = new javax.swing.JLabel();
        bt_rechercher1 = new javax.swing.JButton();
        bt_reussite = new javax.swing.JButton();
        bt_echec = new javax.swing.JButton();
        jsp_notes = new javax.swing.JScrollPane();
        jt_lister = new javax.swing.JTable();
        lbl_reussiteOuEchec = new javax.swing.JLabel();
        lbl_erreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pann_cohortes.setBackground(new java.awt.Color(0, 0, 0));
        pann_cohortes.setForeground(new java.awt.Color(0, 0, 0));

        lbl_titre.setBackground(new java.awt.Color(102, 255, 51));
        lbl_titre.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        lbl_titre.setForeground(new java.awt.Color(102, 255, 204));
        lbl_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titre.setText("COHORTES");

        lbl_logo.setText("");

        bt_deco.setBackground(new java.awt.Color(102, 255, 204));
        bt_deco.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        bt_deco.setText("Déconnexion");
        bt_deco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_deco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_decoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pann_cohortesLayout = new javax.swing.GroupLayout(pann_cohortes);
        pann_cohortes.setLayout(pann_cohortesLayout);
        pann_cohortesLayout.setHorizontalGroup(
            pann_cohortesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pann_cohortesLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(bt_deco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pann_cohortesLayout.setVerticalGroup(
            pann_cohortesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addGroup(pann_cohortesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bt_deco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_nompage.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        lbl_nompage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nompage.setText("Lister");

        pann_menu.setBackground(new java.awt.Color(153, 153, 153));

        bt_rechercher.setBackground(new java.awt.Color(102, 255, 204));
        bt_rechercher.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        bt_rechercher.setForeground(new java.awt.Color(0, 0, 0));
        bt_rechercher.setText("Rechercher");
        bt_rechercher.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercherActionPerformed(evt);
            }
        });
        bt_rechercher.addMouseListener( new btMouseListener());

        bt_afficher.setBackground(new java.awt.Color(102, 255, 204));
        bt_afficher.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        bt_afficher.setForeground(new java.awt.Color(0, 0, 0));
        bt_afficher.setText("Afficher");
        bt_afficher.addMouseListener( new btMouseListener());

        bt_lister.setBackground(new java.awt.Color(102, 255, 204));
        bt_lister.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        bt_lister.setForeground(new java.awt.Color(0, 0, 0));
        bt_lister.setText("Lister");
        bt_lister.addMouseListener( new btMouseListener());

        javax.swing.GroupLayout pann_menuLayout = new javax.swing.GroupLayout(pann_menu);
        pann_menu.setLayout(pann_menuLayout);
        pann_menuLayout.setHorizontalGroup(
            pann_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pann_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pann_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_afficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_lister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pann_menuLayout.setVerticalGroup(
            pann_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pann_menuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bt_rechercher)
                .addGap(48, 48, 48)
                .addComponent(bt_afficher, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(bt_lister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pann_lister.setBackground(new java.awt.Color(153, 153, 153));

        lbl_annee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_annee.setText("Année :");

        text_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_anneeActionPerformed(evt);
            }
        });
        text_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_anneeActionPerformed(evt);
            }
        });
        text_annee.addKeyListener(new KeyListener() {

            public void keyTyped(KeyEvent e) {

            }

            public void keyPressed(KeyEvent e) {

                if (e.getKeyCode() == KeyEvent.VK_ENTER)

                bt_rechercher1.doClick(0);

            }

            public void keyReleased(KeyEvent e) {

            }

        });

        lbl_intitule.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_intitule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_intitule.setText("recherche par :");

        bt_rechercher1.setBackground(new java.awt.Color(102, 255, 204));
        bt_rechercher1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        bt_rechercher1.setForeground(new java.awt.Color(0, 0, 0));
        bt_rechercher1.setText("OK");
        bt_rechercher1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_rechercher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercher1ActionPerformed(evt);
            }
        });
        bt_rechercher.addMouseListener( new btMouseListener());

        javax.swing.GroupLayout pann_rechercheLayout = new javax.swing.GroupLayout(pann_recherche);
        pann_recherche.setLayout(pann_rechercheLayout);
        pann_rechercheLayout.setHorizontalGroup(
            pann_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pann_rechercheLayout.createSequentialGroup()
                .addGroup(pann_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pann_rechercheLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbl_intitule, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pann_rechercheLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pann_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_annee, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(lbl_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_rechercher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pann_rechercheLayout.setVerticalGroup(
            pann_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pann_rechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_intitule, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bt_rechercher1)
                .addGap(299, 299, 299))
        );

        bt_reussite.setBackground(new java.awt.Color(0, 0, 0));
        bt_reussite.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_reussite.setForeground(new java.awt.Color(0, 204, 204));
        bt_reussite.setText("Reussite");
        bt_reussite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reussiteActionPerformed(evt);
            }
        });

        bt_echec.setBackground(new java.awt.Color(0, 0, 0));
        bt_echec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_echec.setForeground(new java.awt.Color(0, 204, 204));
        bt_echec.setText("Echec");
        bt_echec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_echecActionPerformed(evt);
            }
        });

        jt_lister.setBackground(new java.awt.Color(153, 153, 153));
        jt_lister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jt_lister.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_lister.setForeground(new java.awt.Color(0, 0, 0));
        jt_lister.setRowHeight(30);
        jt_lister.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Etudiant", "Nom", "Prenom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jsp_notes.setViewportView(jt_lister);

        lbl_reussiteOuEchec.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_reussiteOuEchec.setVisible(false);

        javax.swing.GroupLayout pann_listerLayout = new javax.swing.GroupLayout(pann_lister);
        pann_lister.setLayout(pann_listerLayout);
        pann_listerLayout.setHorizontalGroup(
            pann_listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pann_listerLayout.createSequentialGroup()
                .addGroup(pann_listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pann_listerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_reussite, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_echec, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pann_listerLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jsp_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pann_listerLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lbl_reussiteOuEchec, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(pann_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pann_listerLayout.setVerticalGroup(
            pann_listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pann_listerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pann_listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pann_listerLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(pann_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pann_listerLayout.createSequentialGroup()
                        .addGroup(pann_listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_reussite)
                            .addComponent(bt_echec))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_reussiteOuEchec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jsp_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        lbl_erreur.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_erreur.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_erreur, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nompage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pann_cohortes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pann_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(pann_lister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pann_cohortes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nompage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_erreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pann_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pann_lister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1420, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercherActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_bt_rechercherActionPerformed

    private void bt_decoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_decoActionPerformed
        int input = JOptionPane.showConfirmDialog(this, "Quitter l'application ?","", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input == JOptionPane.OK_OPTION) {
            Connexion co = new Connexion();
            this.setVisible(false);
            co.setVisible(true);
        } else if (input == JOptionPane.CANCEL_OPTION) {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }

    }//GEN-LAST:event_bt_decoActionPerformed

    private void bt_rechercher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercher1ActionPerformed
            bt_reussite.doClick(0);

    }//GEN-LAST:event_bt_rechercher1ActionPerformed

    private void text_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_anneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_anneeActionPerformed

    private void bt_reussiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reussiteActionPerformed
  
        test_table();
        lbl_reussiteOuEchec.setVisible(true);
        lbl_reussiteOuEchec.setText("Etudiants Admis");
        DefaultTableModel modele= (DefaultTableModel)jt_lister.getModel();
        jt_lister.setDefaultRenderer(Object.class, new DefaultTableCellRenderer());
             
        try
        {
            
            String recherche=text_annee.getText();
            st=cnx.createStatement();
            if(recherche.equals(""))
            {
            rst=st.executeQuery("Select * from notess4, etudiants where etudiants.NE=notess4.NE and res like'ADM'");  
            }
            else
            {
            rst=st.executeQuery("Select * from notess4, etudiants where etudiants.NE=notess4.NE and res like'ADM' and Annee='"+recherche+"'");
            }
                while(rst.next())
                {
                    String NE=rst.getString("NE");
                    String Nom=rst.getString("Nom");
                    String Prenom=rst.getString("Prenom");
                                        
                    modele.addRow(new Object[]{NE,Nom,Prenom});

            
                }
    
        }
        catch(Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_bt_reussiteActionPerformed

    private void bt_echecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_echecActionPerformed
        // TODO add your handling code here:
         
        test_table();
        lbl_reussiteOuEchec.setText("Etudiants Refusé");
        DefaultTableModel modele= (DefaultTableModel)jt_lister.getModel();
        jt_lister.setDefaultRenderer(Object.class, new DefaultTableCellRenderer());
             
        try
        {

            String recherche=text_annee.getText();
            st=cnx.createStatement();
             if(recherche.equals(""))
            {
            rst=st.executeQuery("Select * from notess4, etudiants where etudiants.NE=notess4.NE and res not like'ADM'");  
            }
            else
            {
            rst=st.executeQuery("Select * from notess4, etudiants where etudiants.NE=notess4.NE and res not like'ADM' and Annee='"+recherche+"'");
            }
           
                while(rst.next())
                {
                    String NE=rst.getString("NE");
                    String Nom=rst.getString("Nom");
                    String Prenom=rst.getString("Prenom");
                                        
                    modele.addRow(new Object[]{NE,Nom,Prenom});

            
                }
    
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bt_echecActionPerformed
     private void test_table()
    {
        
        DefaultTableModel modele= (DefaultTableModel)jt_lister.getModel();
        int l=modele.getRowCount();
        if(l>0)
        {
              for(int i =l; i > 0; --i) 
            {
                modele.removeRow(i-1);
            }
        }
    }
    class btMouseListener implements MouseListener 
        {

        int a=0,l=0,r=0;
        @Override
        public void mouseClicked(MouseEvent e) 
            {
            }
        @Override
        public void mousePressed(MouseEvent e)
            {
                if(e.getSource()==bt_rechercher)
                {
                    setVisible(false);
                    new Rechercher().setVisible(true);
                }
                if(e.getSource()==bt_afficher)
                {
                    setVisible(false);
                    new Afficher().setVisible(true);
                }
                 if(e.getSource()==bt_lister)
                {
                    setVisible(false);
                    new Accueil().setVisible(true);
                }
            }
                

        @Override
        public void mouseReleased(MouseEvent e) 
        {
           
        }

        @Override
        public void mouseEntered(MouseEvent e) 
        {
       
        }

        @Override
        public void mouseExited(MouseEvent e)
        {
          
        }
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lister maFenetre = new Lister();
                maFenetre.setVisible(true);
                maFenetre.setSize(1400,800);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_afficher;
    private javax.swing.JButton bt_deco;
    private javax.swing.JButton bt_echec;
    private javax.swing.JButton bt_lister;
    private javax.swing.JButton bt_rechercher;
    private javax.swing.JButton bt_rechercher1;
    private javax.swing.JButton bt_reussite;
    private javax.swing.JScrollPane jsp_notes;
    private javax.swing.JTable jt_lister;
    private javax.swing.JLabel lbl_annee;
    private javax.swing.JLabel lbl_erreur;
    private javax.swing.JLabel lbl_intitule;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nompage;
    private javax.swing.JLabel lbl_reussiteOuEchec;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JPanel pann_cohortes;
    private javax.swing.JPanel pann_lister;
    private javax.swing.JPanel pann_menu;
    private javax.swing.JPanel pann_recherche;
    private javax.swing.JTextField text_annee;
    // End of variables declaration//GEN-END:variables
}
